<div class="row">
    <div class="col">
        <h1 class="text-center">&#8904; ABOUT US &#8904;</h1>
    </div>
</div>

<div class="row">
    <div class="col mt-5">
        <h3 class="text-center">&#8904; Doe Bespoke & Bespoke 1849</h3>
        <p>We offer two fully bespoke tailoring services to suit our clients.Bespoke 1849 is our celebrated bespoke tailoring service, little changed since the original founding of the house to the present day. Enjoy a John Doe tailored suit cut and crafted by the best hands in the business.
            Doe Bespoke is the ultimate new bespoke offering for the time-conscious modern gentleman. A bespoke suit costs from $5000, and is delivered between 6 to 8 weeks. This bespoke service offers the same unmatched quality and prestige from one of the most iconic houses on John Doe, optimised for a more convenient bespoke experience.</p>
    </div>
    <div class="col mt-5">
        <h3 class="text-center">&#8904; Bespoke Shirts</h3>
        <p>Our clients deserve the best of bespoke when it comes to choosing a tailor-made suit, and with our bespoke shirting service this is reflected in every aspect of your wardrobe.As the style and tailored fit of the shirt is an essential part of your comfort and elegance, you leverage your trusted relationship with your cutter, who knows exactly what colours, patterns and style suits you.</p>
    </div>
</div>
<div class="row">
    <div class="col mt-5">
        <h3 class="text-center">&#8904; Classically Contemporary Tweeds</h3>
        <p>Once inseparable from country life, now the choice of the well-dressed around the world. A signature collection of subtle tones and distinctive, bold checks available only in limited editions.The thrill of seeing your tweed come from loom to tailor-made garment is insurmountable. From classic country-tones to contemporary tweeds for city wear, you’ll come to realise why we are known as the house of bespoke tweeds. In the heart of John Doe, we are the only bespoke tailors to offer you the opportunity to design your own tweed have it sampled in-house, for the ultimate tweed experience. Our tweed tailored suits and accessories can be as bold and brilliant or as subtle and sophisticated as you like, get inspired with our archive tweed ledgers and let us guide you through the entire process, for a bespoke tweed service like none other.</p>
    </div>
    <div class="col mt-5">
        <h3 class="text-center">&#8904; Inherited Alteration Service</h3>
        <p>You’ll come to appreciate the true value and quality of a bespoke suit when you’re still enjoying it in 20 years’ time. Our garments aren’t just tailor-made to look fantastic, they’re made to last a lifetime and with proper care, can last several lifetimes, making a bespoke commission a worthy investment.This is why we now pleased to offer a service for clients who have inherited a Doe suit or jacket from a loved one. You are invited to bring the garment in store for an appraisal with a Doe tailor to assess the work required to reimagine your garment.Perhaps it’s a much loved bespoke suit, passed down from a parent, which you’ve been longing to wear, or indeed pass down yourself. Now we invite you back, to breathe new life into your bespoke clothing.</p>
    </div>
</div>


