<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'template/head.phtml' ?>
  </head>
<body>
  <section class="font-monospace">
    <?php include_once 'template/menu.phtml' ?>
    <div class="container mt-5">
      <div class="row" class="vh-100">
        <?=$content?>
      </div>
      <?php include_once 'template/footer.phtml' ?>
    </div>
    
  </section>
  <?php include_once 'template/javascript.phtml' ?>
</body>
</html>



