<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Customers</h1>
        </div>
    </div>
    <hr>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>City</th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach ($customers as $customer) : ?>
                <tr>
                    <td><?= $customer->id ?></td>
                    <td><?= $customer->firstname ?></td>
                    <td><?= $customer->lastname ?></td>
                    <td><?= $customer->email?></td>
                    <td><?= $customer->city?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>