<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Cart</h1>
        </div>
    <?php if (empty($cart)) : ?>
        <div class="no-cart text-center">
            <h2>Cart empty!</h2>
            <h5>Back to products <a href="<?= App::config('url'); ?>publicproduct/index">here</a></h5>
        </div>
    <?php else : ?>
    </div>
    <hr>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Total Price</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($cart as $product) : ?>
                <tr>
                    <td><?= $product->id ?></td>
                    <td><?= $product->iname ?></td>
                    <td><?= $product->price ?> €</td>
                    <td> 
                    <?php if ($product->cart == 0): ?>
                        <a onclick="return confirm('Are you sure you want to delete?');"  href="<?= App::config('url') ?>product/delete/<?=$product->id?>">
                            <i title="Delete" class="bi bi-trash" style="color:red; float:right; font-size: 2rem;"></i>
                        </a>
                    <?php else:?>
                        <i  title="Cannot delete" class="bi bi-trash" style="color:gray; float:right; font-size: 2rem;"></i>
                    <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>