<form action="<?= App::config('url') ?>customer/addNew" method="post">

    <fieldset>
    <legend class="text-center">Add new User</legend>

    <div class="form-row">
        <div class="col d-flex justify-content-center">
            <label class="p-3">                
             <input type="text" name="firtsname" class="form-control" placeholder="Name" value="<?=$customer->firstname?>"/>
            </label>

            <label class="p-3">            
                <input type="text" name="lastname" class="form-control" placeholder="Last name" value="<?=$customer->lastname?>"/>
            </label>
        </div>
    </div>
    <div class="form-row">
        <div class="col d-flex justify-content-center">
            <label class="p-3">              
                <input type="text" name="password" class="form-control" placeholder="password" value="<?=$customer->userpassword?>"/>
            </label>

            <label class="p-3">
                <input type="text" name="email" class="form-control" placeholder="email" value="<?=$customer->email?>"/>
            </label>
        </div>
    </div>

        <div class="row">
            <div class="col d-flex justify-content-end">
                <a  class="btn btn-outline-danger" 
                href="<?=App::config('url')?>customer/index">Cancel</a>
            </div>
            <div class="col">
                <input type="submit" class="btn btn-outline-success" value="Add new">
            </div>
        </div>
        <?=$message?>
    </fieldset>
</form>