<div class="row">
    <hr / class="mt-5">
    <div class="col">       
        <p class="footer">
            <?=App::config('titleApp')?> &copy; 2022
        </p>   

        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-facebook h4" ></i>
        </a>
        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-twitter h4"></i>
        </a>
        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-google h4"></i>
        </a>
        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-instagram h4"></i>
        </a>
        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-youtube h4"></i>
        </a>
        <a href="#"  class="text-decoration-none text-muted">
            <i class="bi bi-github h4"></i>
        </a>

    </div>
    <div class="col">
        <a href="#">
            <img src="<?=App::config('url')?>public/img/logo.png" class="rounded mx-auto d-block" alt="John Doe Tailoring logo">
        </a>
    </div>
</div>