<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"><?=App::config('titleApp')?></a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>about/index">About</a>
        </li>
        <?php if(App::authorized()):?>
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>product/index">Product</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link " href="<?=App::config('url')?>dashboard/index">Dashboard</a>
        </li>
          <?php if(App::admin()):?>
        <li class="dropdown nav-item">
          <a class=" dropdown-toggle nav-link " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Admin/Operator
        </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li class="nav-item">
                  <a class="dropdown-item" href="<?=App::config('url')?>product/index">Product</a>
                </li>
                <li class="nav-item">
                  <a class="dropdown-item" href="<?=App::config('url')?>customer/index">Customer</a>
                </li>
            </ul>
        </li>
          <?php endif;?>
        <?php endif;?>
      </ul>
      <ul class="d-flex navbar-nav">
        <li class="nav-item">
          <?php if(App::authorized()):?>
            <a class="nav-link " href="<?=App::config('url')?>login/logout">Logout <?php echo $_SESSION['authorized']->firstname ?></a>
          <?php else:?>
            <a class="nav-link" href="<?=App::config('url')?>login/index">Login</a>
          <?php endif;?>
        </li>
        <?php if(App::authorized()):?>
        <li class="nav-item">
          <a href="<?=App::config('url')?>cart/index" class="btn btn-sm">
            <i class="bi bi-basket3 h5"></i>
          </a>
        </li>
        <?php endif;?>
      </ul>
    </div>
  </div>
</nav>

