<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"><?=App::config('titleApp')?></a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>about/index">About</a>
        </li>
        <?php if(App::authorized()):?>
        <li class="nav-item">
          <a class="nav-link" href="<?=App::config('url')?>product/index">Product</a>
        </li>
        <?php endif;?>
        <?php if(App::authorized()):?>
        <li>
          <a class="nav-link " href="<?=App::config('url')?>dashboard/index">Dashboard</a>
        </li>
        <?php endif;?>
        <?php if(App::authorized()):?>
        <li class="dropdown">
          <a class=" dropdown-toggle nav-link " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Admin/Operator
        </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="<?=App::config('url')?>product/index">Product</a></li>
                <li><a class="dropdown-item" href="<?=App::config('url')?>customer/index">Customer</a></li>
            </ul>
        </li>
        <?php endif;?>
      </ul>
      <ul class="d-flex navbar-nav">
        <li class="nav-item">
          <?php if(App::authorized()):?>
            <a class="nav-link " href="<?=App::config('url')?>login/logout">Logout <?php echo $_SESSION['authorized']->firstname ?></a>
          <?php else:?>
            <a class="nav-link" href="<?=App::config('url')?>login/index">Login</a>
          <?php endif;?>
        </li>
        <li class="nav-item">
          <a href="" class="btn btn-sm">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-basket3" viewBox="0 0 16 16">
              <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
            </svg>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

