<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('titleApp')?></li>
      <li><a href="<?=App::config('url')?>">Home</a></li>
      <li>
        <a href="#">About</a>
      </li>
      <li><a href="#">Products</a></li>
      <?php if(App::authorized()):?>
        <li><a href="<?=App::config('url')?>dashboard/index">Dashboard</a></li>
      <?php endif;?> 
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    <ul class="menu">
      <li>
        <?php if(App::authorized()):?>
          <a href="<?=App::config('url')?>login/logout">Logout <?php echo $_SESSION['authorized']->name ?></a>
        <?php else:?>
          <a href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
      
      <li>
        <a href="#"><i class="fi-shopping-cart size-60"></i></a>
      </li>
    </ul>
  </div>
</div>