<form action="<?=App::config('url')?>radionica/promjeni" method="post">

<div class="grid-x grid-padding-x">
    <div class="cell large-6">
   
        <fieldset>
            <legend>Promjena postojeće radionice</legend>


            <label>
                Naziv
                <input type="text" name="naziv" value="<?=$e->naziv?>" />
            </label>

            <label>
                Smjer
                <select name="tecaj">
                    <?php foreach($tecajevi as $tecaj): ?>
                        <option 
                        <?php if($tecaj->sifra==$e->tecaj){
                            echo 'selected="selected"';
                        } ?>
                        value="<?=$tecaj->sifra?>"><?=$tecaj->naziv?></option>
                    <?php endforeach;?>
                </select>
            </label>

            <div class="warning callout">
         
                    <input type="text" id="uvjetTrenera" placeholder="Traži trenera">

                Odabrani Trener: <p id="odabraniTrenera"><?=$labelaTrenera; ?></p>
            </div>
            

            <label>
                Datum početka
                <input type="date" name="datumpocetka" value="<?php 
                if($e->datumpocetka==null){
                    echo '';
                }else{
                    echo date('Y-m-d',strtotime($e->datumpocetka));
                }
                ?>" lang="hr-HR">
                    </label>
        

            <input type="hidden" name="sifra" value="<?=$e->sifra?>">
            <input type="hidden" id="trener" name="trener" value="<?=$e->trener?>">

            
            <?=$poruka?>

        </fieldset>
      
    </div>
    <div class="cell large-6">
    <input type="text" id="uvjet" placeholder="Traži plesača">
        <div style="overflow: auto; max-height: 400px; margin-bottom: 20px;">

               
                <table >
                <thead>
                    <tr>
                        <th>Plesač</th>
                        <th>Akcija</th>
                    </tr>
                </thead>
                <tbody id="plesaci">
                    <?php foreach($e->plesac as $p): ?>
                        <tr>
                            <td><?=$p->ime?> <?=$p->prezime?></td>
                            <td>
                            
                                <a onclick="return confirm('Sigurno obrisati?');" 
                                id="b_<?=$p->sifra?>"
                                class="brisiPlesaca"
                                href="#">
                                    <i style="color: red; font-size:30px;" title="Obriši" 
                                    class="bi bi-trash-fill bi-3x""></i>
                                </a>  
                        
                            
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="grid-x grid-padding-x">
    <div class="large-4 cell">
        <a  class="alert button expanded" 
        href="<?=App::config('url')?>radionica/odustani/<?=$e->sifra?>">Odustani</a>
    </div>
    <div class="large-8 cell">
        <input type="submit" class="success button expanded" value="Promjeni">
    </div>
</div>

</form>