<div class="grid-x">
    <div class="cell large-auto">
        <h1 class="text-center">
            &#8904;WELCOME&#8904;
        </h1>
        <p>
            <span>E</span>xperience for yourself the luxury of John Doe tailoring. Handmade suits, with a tailored fit and feel that is incomparable to anything else you’ll wear.
        </p>
    
        <p>
            <span>W</span>e make the world’s finest handcrafted clothes. Bespoke designs that you will love for a lifetime. Our extensive tailoring services celebrate the very best that the human hand can make and that money can buy. You can expect over 180 years of tailoring expertise, lovingly stitched in every bespoke garment.
        </p>
        <p>
            <span>O</span>ur bespoke tailoring services start at $5000 for a  two-piece bespoke suit. For the same cost as a regular made-to-measure service, you can now enjoy a fully bespoke experience from the legendary John Doe tailoring house.
        </p>
        <a class="hollow button secondary" href="<?=App::config('url')?>about/index">More</a>
    
        <figure class="mt-3">
            <blockquote class="blockquote">
                <p>
                    "Just because a suit fits, doesn't mean it looks good. You need a tailor. You want to get bespoke."
                </p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Ryan Tedder
            </figcaption>
        </figure>

        <figure>
            <blockquote class="blockquote">
                <p>
                    "Clothes make the man. Naked people have little or no influence on society."
                </p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Mark Twain
            </figcaption>
        </figure>
    
        <figure>
            <blockquote class="blockquote">
                <p>
                     "A tailor can adapt to any medium, be it poetry, be it criticism. As a poet, he can mend, and with the scissors of criticism he candivide."
                </p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Franz Grillparzer
            </figcaption>
        </figure>
    
        <figure>
            <blockquote class="blockquote">
                <p>
                    "If you are out to describe the truth, leave elegance to the tailor."
                </p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Albert Einstein
            </figcaption>
        </figure>

        <figure>
            <blockquote class="blockquote">
                <p>
                    "The only person who acts sensibly is my tailor. He takes my measure anew every time he sees me. Everyone else goes by their old measurements." 
                </p>
        </blockquote>
            <figcaption class="blockquote-footer">
                George Bernard Shaw
            </figcaption>
        </figure>
    </div>  
    <div class="cell large-auto">
        <img src="<?=App::config('url')?>public/img/main.png"  alt="John Doe Tailoring">
    </div> 
</div>
