<div style="text-align: center">
    <h1>DOBRO DOŠLI</h1>
</div>
<div class="grid-x grid-padding-x" style="text-align: center; margin-top:80px;">
    
    <div class="large-6 cell">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
    </div>
    <div class="large-6 cell">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto          reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit itaque repudiandae ratione, minima quaerat quibusdam!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iusto reprehenderit id minima tempora odit esse voluptatibus! Debitis atque ipsam qui est illum laboriosam, in eum, dolores corrupti porro repellat!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit nobis praesentium atque asperiores magni et dolore incidunt est voluptate dolor.</p>
    </div>
</div>
