<div class="registration-main">
    <form action="<?= App::config('url') ?>registration/newCustomer" method="POST">
        <h2 class="text-center">Registracija</h2>
        <p class="text-center">Ukoliko imate račun, prijavite se <a href="<?= App::config('url') ?>login/index">ovdje.</a></p>
        <div class="grid-x registration-together">

            <div class="large-6 medium-12 cell registration-part">
                <legend>Mandatory:</legend>

                <label for="firstname">First name</label>
                <input type="text" name="firstname" id="firstname" aria-describedby="messageFirstname" value="<?= $customer->firstname ?>">
                <p class="help-text red-message" id="messageFirstname">
                    <?= $message->firstname ?>
                </p>

                <label for="lastname">Last name</label>
                <input type="text" name="lastname" id="lastname" aria-describedby="messageLastname" value="<?= $customer->lastname ?>">
                <p class="help-text red-message" id="messageLastname">
                    <?= $message->lastname ?>
                </p>

                <label for="email">Email</label>
                <input type="email" name="email" id="email" aria-describedby="messageEmail" placeholder="vas.email@gmail.com" value="<?= $customer->email ?>">
                <p class="help-text red-message" id="messageEmail">
                    <?= $message->email ?>
                </p>

                <label for="user_password">Password</label>
                <input type="password" name="user_password" id="user_password" aria-describedby="messagePassword" value="<?= $customer->userpassword ?>">
                <p class="help-text red-message" id="messagePassword">
                    <?= $message->user_password ?>
                </p>

            </div>

            <div class="large-6 medium-12 cell registration-part">
                <legend>Optional:</legend>

                <label for="phonenumber">Phonenumber</label>
                <input type="number" name="phonenumber" id="phonenumber" aria-describedby="messagePhoneNumber" placeholder="0123456789" value="<?= $customer->phonenumber ?>">
                <p class="help-text red-message" id="messagePhoneNumber">
                    <?= $message->phonenumber ?>
                </p>

                <label for="street">Street and street number</label>
                <input type="text" name="street" id="street" aria-describedby="messageStreet" placeholder="Ulica Republike, 3a" value="<?= $customer->street ?>">
                <p class="help-text red-message" id="messageStreet">
                    <?= $message->street ?>
                </p>

                <label for="city">City</label>
                <input type="text" name="city" id="city" aria-describedby="messageCity" placeholder="Osijek" value="<?= $customer->city ?>">
                <p class="help-text red-message" id="messageCity">
                    <?= $message->city ?>
                </p>

                <label for="postalnumber">Postal number</label>
                <input type="number" name="postalnumber" id="postalnumber" aria-describedby="messagePostalNumber" placeholder="31000" value="<?= $customer->postalnumber ?>">
                <p class="help-text red-message" id="messagePostalNumber">
                    <?= $message->postalnumber ?>
                </p>
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="registration-button" value="Registriraj se!">Registriraj se!</button>
        </div>
    </form>
</div>