<form action="<?=App::config('url')?>trener/akcija" method="post"
enctype="multipart/form-data">

    <fieldset>
        <legend>Detalji trenera</legend>

        <label>Ime</label>    
        <input type="text" name="ime" value="<?=$trener->ime?>" />
        
        <label for="prezime">Prezime</label>
        <input type="text" name="prezime" id="prezime" 
         value="<?=$trener->prezime?>">

        <label for="email">Email</label>
        <input type="email" name="email" id="email" value="<?=$trener->email?>">

        <label for="oib">OIB</label>
        <input type="text" name="oib" id="oib" value="<?=$trener->oib?>">

        <label for="ples">Ples</label>
        <input type="text" name="ples" id="ples" value="<?=$trener->ples?>">

        <input type="hidden" name="sifra" value="<?=$trener->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>trener/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="<?=$akcija?>">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>