<div class="grid-x ">
<div class="cell large-6">
        <h1 style="font-size: 1.5rem;">Treneri</h1>
    </div>
    <div class="cell large-6" style="text-align: right;">
        <a href="<?=App::config('url')?>trener/detalji">
            <i style="color: green;" title="Dodaj novi" 
                class="fas fa-2x fa-plus-circle"></i>
        </a>
    </div>

<table class="table-sort table-sort-search">
    <thead>
        <tr>
            <th class="table-sort">Ime</th>
            <th class="table-sort">Prezime</th>
            <th class="table-sort">Email</th>
            <th class="table-sort">Ples</th>
            <th>Opcija</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($treneri as $trener): ?>
            <tr>
                <td><?=$trener->ime?></td>
                <td><?=$trener->prezime?></td>
                <td><?=$trener->email?></td>
                <td><?=$trener->ples?></td>
                
                
                <td>
                <a href="<?=App::config('url')?>trener/detalji/<?=$trener->sifra?>">
                    <i title="Promjeni" 
                        class="fas fa-2x fa-edit"></i>
                </a>   
                <?php if($trener->radionica==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?');" style="margin-left: 20px;" href="<?=App::config('url')?>trener/brisanje/<?=$trener->sifra?>">
                        <i style="color: red; font-size:30px;" title="Obriši " 
                            class="bi bi-trash-fill"></i>
                    </a>  
                <?php else:?>
                    <i style="margin-left: 20px;color: gray; font-size:30px;" 
                    title="Ne može se obrisati" 
                        class="bi bi-trash-fill"></i>
                <?php endif;?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>   
    
</div>
