<div class="structure">
    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa et consectetur molestiae ex adipisci quia commodi, voluptates perferendis. Reiciendis eligendi earum aut ex quas tempore. Dolor, mollitia cupiditate! Consectetur laborum quod quam tempore cupiditate. Nulla eligendi modi ducimus totam suscipit.</p>
        </div>
        <div class="large-6 cell">
            <img src="<?=App::config('url')?>public/img/main.png" alt="John Doe Tailoring">
        </div>
    </div>
</div>