<form class="log-in-form" action="<?=App::config('url')?>login/authorization" method="POST">
  <h4 class="text-center">Log in</h4>
  <label>Email
    <input type="email" placeholder="somebody@example.com" value="<?=$email?>" />>
  </label>
  <label>Password
    <input type="password" pname="password">
  </label>
  <input id="show-password" type="checkbox"><label for="show-password">Show password</label>
  <p><input type="submit" class="button expanded" value="Log in"></input></p>
  <p class="text-center"><a href="#">Forgot your password?</a></p>
  <?=$message?>
</form>


