<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'template/head.phtml' ?>
  </head>
<body>
    <?php include_once 'template/menu.phtml' ?>
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
            <div class="callout" id="program">
                <?=$content?>
            </div>
        </div>
      </div>
      <?php include_once 'template/footer.phtml' ?>
    </div>
    
    <?php include_once 'template/javascript.phtml' ?>
  </body>
</html>