<form action="<?= App::config('url') ?>product/action" method="POST" enctype="multipart/form-data">
<fieldset>
        <legend><h1><?=$title?></h1></legend>

    <label for="iname">Name</label>
    <input type="text" name="iname" id="iname" value="<?= $product->iname ?>">

    <label for="price">Price</label>
    <input type="text" name="price" id="price" value="<?= $product->price ?>">

    <label for="idescription">Description</label>
    <input type="text" name="idescription" id="idescription" value="<?= $product->idescription ?>">

    <input type="hidden" name="id" value="<?=$product->id?>">

    <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" href="<?=App::config('url')?>product/index">Cancel</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="<?=$action?>">
            </div>
    </div>

    </fieldset>

</form>




