<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Products</h1>
        </div>
        <div class="cell large-6" style="text-align: right;">
            <a href="<?= App::config('url') ?>product/details"><i style="color: green;" title="Add new product" class="fas fa-2x fa-plus-circle"></i></a>
        </div>
    </div>
    <hr>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td><?= $product->id ?></td>
                    <td><?= $product->iname ?></td>
                    <td><?= $product->idescription ?></td>
                    <td><?= $product->price ?> €</td>
                    <td> 
                    <?php if ($product->cart == 0): ?>
                        <a onclick="return confirm('Are you sure you want to delete?');"  href="<?= App::config('url') ?>product/delete/<?=$product->id?>">
                            <i title="Delete" class="bi bi-trash" style="color:red; float:right; font-size: 2rem;"></i>
                        </a>
                    <?php else:?>
                        <i  title="Cannot delete" class="bi bi-trash" style="color:gray; float:right; font-size: 2rem;"></i>
                    <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>




        
 