<form action="<?=App::config('url')?>tecaj/promjeni" method="post">

    <fieldset>
        <legend>Promjena postojećeg tečaja</legend>


        <label>Naziv</label>    
        <input type="text" name="naziv" value="<?=$tecaj->naziv?>" />
   
        <label for="trajanje">Trajanje</label>
        <input type="number" name="trajanje" id="trajanje" 
        pattern="[0-9]{10}" value="<?=$tecaj->trajanje?>">

        <label for="cijena">Cijena</label>
        <input type="text" name="cijena" id="cijena" value="<?=$tecaj->cijena?>">

        <p>Certificiran</p>

        <input type="radio" name="certificiran" id="da" 
        <?php if($tecaj->certificiran) echo 'checked="checked"'; ?>
        value="1">
        <label for="da">DA</label>
        <br />
        <input type="radio" name="certificiran" id="ne" 
        <?php if(!$tecaj->certificiran) echo 'checked="checked"'; ?>
        values="0">
        <label for="ne">NE</label>

        <input type="hidden" name="sifra" value="<?=$tecaj->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>tecaj/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Promjeni">
            </div>
        </div>
        <?=$poruka?>
    </fieldset>
</form>