<form class="log-in-form" action="<?=App::config('url')?>login/authorization" method="POST">
  <h4 class="text-center">Log in</h4>
  <label>Email
    <input type="email" name="email" placeholder="admin@edunova.hr" value="<?=$email?>" />
  </label>
  <label>Password
    <input type="password" name="password" placeholder="a">
  </label>
  <p>
    <input type="submit" class="button expanded" value="Login"></input>
  </p>
  <?=$message?>
</form>


