<div class="grid-x grid-padding-x"> 
    <div class="large-3 medium-4 cell">
        <div class="category">
            <div class="product">                   
                <div class="imgBx">
                    <img src="">
                </div>
                <div class="content">
                    <h2>
                        Lorem, ipsum dolor.
                    </h2>
                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing 
                        elit. Laudantium iusto maxime corporis 
                        quaerat deserunt nihil nobis sit doloribus quas sint fugit, 
                        qui dolorum laborum reiciendis dolorem excepturi mollitia facilis 
                        nulla.
                    </p>
                </div>  
            </div>   
        </div>         
    </div>
</div>