<form action="<?= App::config('url') ?>customer/changing" method="post">

    <fieldset>

    <legend class="text-center">Change an existing customer</legend>

    <div class="form-row">
        <div class="col d-flex justify-content-center">
            <label class="p-3">                
             <input type="text" name="firtsname" class="form-control" placeholder="Name" value="<?=$customer->firstname?>"/>
            </label>

            <label class="p-3">            
                <input type="text" name="lastname" class="form-control" placeholder="Last name" value="<?=$customer->lastname?>"/>
            </label>
        </div>
    </div>
    <div class="form-row">
        <div class="col d-flex justify-content-center">
            <label class="p-3">              
                <input type="text" name="password" class="form-control" placeholder="password" value="<?=$customer->userpassword?>"/>
            </label>

            <label class="p-3">
                <input type="text" name="email" class="form-control" placeholder="email" value="<?=$customer->email?>"/>
            </label>
        </div>
    </div>
        <input type="hidden" name="id" value="<?=$customer->id?>">


        <div class="row">
            <div class="col d-flex justify-content-end">
                <a  class="btn btn-outline-danger" 
                href="<?=App::config('url')?>customer/index">Cancel</a>
            </div>
            <div class="col">
                <input type="submit" class="btn btn-outline-success btn-sm" value="Change">
            </div>
        </div>
        <?=$message?>

    </fieldset>
</form>