<div class="col">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">Email</th>      
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
            </tr>
        </thead>
        
        <tbody>
           <?php foreach($customers as $customer): ?>
                <tr>
                    <td><?=$customer->email?></td>
                    <td><?=$customer->firstname?></td>
                    <td><?=$customer->lastname?></td>                   
                </tr>
            <?php endforeach;?>   
        </tbody>
    </table>