<div class="col">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Password</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col"><a href="<?= App::config('url') ?>customers/new"><i style="color:green;" class="bi bi-plus-square"></i></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($customer as $customers):?>
                <tr>
                    <th scope="row"><?= $customers->id ?></th>
                    <td><?= $customers->email ?></td>
                    <td><?= $customers->userpassword ?></td>
                    <td><?= $customers->firstname ?></td>
                    <td><?= $customers->lastname ?></td>
                    <td>
                        <a href="<?= App::config('url') ?>customer/change/=<? $customer->id?>">
                            <i title="Change &quot;<?= $customers->firstname?>&quot;" class="bi bi-recycle"></i>
                        </a>
                        <?php if ($customer->cart == 0): ?>
                        <a onclick="return confirm('Are you sure you want to delete <?= $customers->firstname?>?');" style="margin-left: 20px;" href="<?= App::config('url') ?>customer/delete/<?=$customers->id?>">
                            <i style="color: red" title="Delete <?= $customers->firstname ?>" class="bi bi-trash"></i>
                        </a>
                        <?php else:?>
                        <i style="margin-left: 20px;color: gray" title="Cannot delete  <?= $customers->firstname?>" class="bi bi-trash"></i>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>