<div class="category">
    <div class="product">                   
        <div class="imgBx">
                <img id=">" src="" alt="">
        </div>
        <div class="content">
            <a href="<?=App::config('url')?>products/details">
            <i style="color: green;" title="Add new" 
                class="fas fa-2x fa-plus-circle"></i>
        </div>                             
    </div>   
</div>