<div class="col">
  <form>

    <div class="form-row">

      <div class="form-group col-md-6">
        <label for="inputProduct">Product name</label>
        <input type="text" class="form-control" id="inputEmail4" placeholder="Product">
      </div>

      <div class="form-group col-md-6">
        <label for="inputPrice">Price</label>
        <input type="text" class="form-control" id="inputPrice" placeholder="price">
      </div>

    </div>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>

      <div class="form-group">
        <label for="exampleFormControlFile1">IMaget</label>
        <input type="file" class="form-control-file" id="exampleFormControlFile1">
      </div>

  </form>
  
</div>