<?php include 'error_report.phtml';?>
<div class="row">
  <?php if(App::admin()):?>
  <?php include 'add.phtml';?>
  <?php endif;?>  
</div>
<hr>
<?php foreach($products as $product): ?>
    <div class="card m-5" style="width: 20rem; min-height:30rem; box-shadow: 0 5px 20px rgba(0,0,0,0.5);">
      <img class="card-img-top" src="<?=$product->picture?>" alt="<?=$product->item_name?>">
        <div class="card-body">
          <h5 class="card-title text-center"><?=$product->item_name?></h5>
          <p class="card-text text-center"><?=$product->item_description?></p>
            <div class="row mt-5">
              <div class="col"><p><?=$product->item_price?> € </p></div>
              <div class="col"><a href="<?=App::config('url')?>cart/index"  data-id="<?= $product->id?>" class="btn btn-outline-warning" style="float:right;">BUY</a></div>
            </div>  
            <?php if(App::admin()):?>
            <div class="row mt-5">
              <div class="col">
                <a href="<?= App::config('url') ?>product/details/=<? $product->id?>">
                  <i title="Change" class="bi bi-pencil-square" style="color:black; font-size:2rem;"></i>
                </a>
              </div>
              <div class="col" >
              <?php if ($product->cart == 0): ?>
                  <a onclick="return confirm('Are you sure you want to delete?');"  href="<?= App::config('url') ?>product/delete/<?=$product->id?>">
                    <i title="Delete" class="bi bi-trash" style="color:red; float:right; font-size: 2rem;"></i>
                  </a>
                  <?php else:?>
                    <i  title="Cannot delete" class="bi bi-trash" style="color:gray; float:right; font-size: 2rem;"></i>
                  <?php endif;?>
              </div>
            </div>
            <?php endif;?> 
        </div>
    </div>
<?php endforeach;?> 

        
 