<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=App::config('naslovApp')?></title>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/foundation.css">
<link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">
<link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
<?php if(isset($css)) echo $css; ?>
