<hr <?php 
if(App::config('dev')){
    echo 'style="border: 1px solid black;"';
}

?> />

<div class="grid-x">
    <div class="cell large-auto">       
        <p>
            <?=App::config('naslovApp')?> &copy; 2022 
        
        </p>   

        
       

    </div>
    <div class="cell large-auto">
       <p style="float:right;"> Mateo Opančar 
            <a href="https://github.com/OpancarM/PP24SQL"  style="color:gray;">
                <i class="bi bi-github h4"></i>
            </a>
       </p>
    </div>
</div>
