<div class="grid-container ">
  <div class="cell large-auto">
    <form action="<?= App::config('url') ?>cart/addtocart" method="POST">
    <div class="card" style="width:213px;">
      <img src="<?= App::config('url')?>public/img/unkown.png" data-open="product<?= $product->id ?>" title="More details!">
      <div class="card-section text-center">   
        <h4></h4> 
        <p><?= $product->idescription ?></p>
        <p><?= $product->price ?> € </p> 
          
          <input type="submit" class="success button expanded" value="<?=$addtocart?>">
          <input type="hidden" name="iname" value="<?= $product->iname ?>">
          <input type="hidden" name="price" value="<?= $product->price ?>">
        </form> 
        
      </div>
    </div>
  </div>
</div>

