<div class="col">
  <form action="<?=App::config('url')?>product/action" method="post" enctype="multipart/form-data">

  <?php if($product->id != 0):?>        
    <div>
        <a onclick="return confirm('Confirm deletion for <?=$product->item_name?> ?')" class="btn btn-outline-danger btn-sm" href="<?=App::config('url')?>product/delete/<?=$product->id?>">Delete product!</a>     
    </div>
    <hr>
  <?php endif;?>

  <legend>Product deatails:</legend>
    <input type="hidden" name="id" value="<?=$product->id?>">
    
    <label for="name">Naziv</label>
    <input type="text" name="name" id="name" aria-describedby="messagename" value="<?= $product->item_name ?>">
    <p class="help-text red-message" id="messagename">
        <?= $message->name ?>
    </p>

    <label for="description">Description</label>
    <input type="text" name="description" id="description" aria-describedby="messagedescription" value="<?= $product->item_description ?>">
    <p class="help-text red-message" id="messagedescription">
        <?= $message->item_description ?>
    </p>

    <label for="price">Price (npr. 125,99)</label>
    <input type="text" name="price" id="price" aria-describedby="messageprice" value="<?= $product->item_price ?>">
    <p class="help-text red-message" id="messageprice">
        <?= $message->item_price ?>
    </p>

    <label for="imageInput">* Change photo *</label>
    <input type="hidden" name="imageInput" id="imageInput" value="<?= $product->imageInput?>" aria-describedby="messageimageinput">
    <p class="help-text red-message" id="messageimageinput">
        <?= $message->imageInput ?>
    </p>
    <img class="picture" id="photo" src="<?= App::config('url')?>public/images/product/<?=$product->id?>.png" alt="<?=$product->item_name?>">
    <br>

     <!-- Modal for CropperJS -->
     <div class="reveal" id="pictureModal" data-reveal>
        <div style="max-height: 600px; overflow: auto;">
            <img id="image" src="" alt="" />
        </div>
        <br>
        <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
        <br>
        <div class="grid-x text-center">
            <div class="large-8 text-center">
                <a class="button expanded" href="#" id="save">Save</a>
            </div>
            <div class="large-4 text-center">
                <button class="button alert" data-close aria-label="Close modal" >Cancel</button>
            </div>
        </div>
    </div>
    <!-- End modal -->


    <fieldset>
    <div class="form-row">

      <div class="col mt-5 d-flex justify-content-center">
        <label for="product" class="p-3 col-6">
          <input type="text" class="form-control" id="product" placeholder="Product" value="<?=$product->item_name?>">
        </label>
      </div>

      <div class="form-group col mt-5 d-flex justify-content-center">
        <label for="price" class="p-3 col-6">
          <input type="text" class="form-control" id="price" placeholder="Price" value="<?=$product->item_price?>">
        </label>
      </div>

      <div class="form-group mt-5 col mt-5 d-flex justify-content-center">
        <label for="description" class="p-3 col-6">
          <textarea class="form-control" id="description1" rows="3" placeholder="Description" value="<?=$product->item_description?>"></textarea>
        </label>
      </div>

      <div class="form-group mt-5 col mt-5 d-flex justify-content-center">
        <label for="picture" class="p-3 col-6">
          <input type="file" id="picture" name="picture">

          <input type="hidden" name="id" value="<?=$product->id?>">
        </label>
      </div>

      <div class="row mt-5">
        <div class="col d-flex justify-content-end">
          <a  class="btn btn-outline-danger btn-sm" href="<?=App::config('url')?>product/index">Cancel</a>
        </div>
        <div class="col">
          <input type="submit" class="btn btn-outline-success btn-sm" value="<?=$action?>">
        </div>
      </div>

      <?=$message?>

    </div>

      
        
    </fieldset>
  </form>
  
</div>