<div class="grid-x" style="margin-top:80px;">
    <div class="cell large-auto">       
        <p class="footer">
            <?=App::config('titleApp')?> &copy; 2022
        </p>   

        <a href="#"  style="color:gray;">
            <i class="bi bi-facebook h4" ></i>
        </a>
        <a href="#"  style="color:gray;">
            <i class="bi bi-twitter h4"></i>
        </a>
        <a href="#"  style="color:gray;">
            <i class="bi bi-google h4"></i>
        </a>
        <a href="#"  style="color:gray;">
            <i class="bi bi-instagram h4"></i>
        </a>
        <a href="#"  style="color:gray;">
            <i class="bi bi-youtube h4"></i>
        </a>
        <a href="#"  style="color:gray;">
            <i class="bi bi-github h4"></i>
        </a>

    </div>
    <div class="cell large-auto">
        <a href="#">
            <img src="<?=App::config('url')?>public/img/logo.png" class="float-right" alt="John Doe Tailoring logo">
        </a>
    </div>
</div>