<?php include_once 'error_report.phtml' ?>
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('titleApp')?></div>
</div>

<div class="top-bar " id="example-menu"style="background-color:transparent;">
  <div class="top-bar-left" >
    <ul class="dropdown menu " style="background-color:transparent;"  data-dropdown-menu>
      <li class="menu-text" ><?=App::config('titleApp')?></li>
      <li>
        <a style="color:black;" href="<?=App::config('url')?>">Home</a>
      </li>
      <li>
        <a style="color:black;" href="<?=App::config('url')?>about/index">About</a>
      </li>
      <?php if(App::authorized()):?>
        <li>
          <a style="color:black;" href="<?=App::config('url')?>publicproduct/index">Product</a>
        </li>
        <li>
          <a style="color:black;" href="<?=App::config('url')?>dashboard/index">Dashboard</a>
        </li>
      <?php if(App::admin()):?>
      <li class="has-submenu">
        <a style="color:black;" href="#0">Admin</a>
        <ul class="submenu menu vertical" data-submenu>
          <li>
            <a style="color:black;" href="<?=App::config('url')?>product/index">Product</a>
          </li>
          <li>
            <a style="color:black;" href="<?=App::config('url')?>customer/index">Customer</a>
          </li>
        </ul>
      </li>
      <?php endif;?> 
      <?php endif;?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu" style="background-color:transparent;">
      <li>
        <?php if(App::authorized()):?>
        <a style="color:black;" href="<?=App::config('url')?>login/logout">Logout <?php echo $_SESSION['authorized']->firstname ?></a>
        <?php else:?>
        <a style="color:black;" href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
      <?php if(App::authorized()):?>
          <?php if (empty($cart)) : ?>
          <li>
            <a style="color:black;" href="<?=App::config('url')?>cart/index" class="btn btn-sm">
              <i class="bi bi-basket3 h5"></i>
            </a>
          </li>
          <?php else : ?>
          <li>
            <a style="color:black;" href="<?=App::config('url')?>cart/index" class="btn btn-sm">
              <i class="bi bi-basket3-fill h5"></i>
            </a>
          </li>
          <?php endif;?>
        <?php endif;?>
    </ul>
  </div>
</div>

